<?php
/******************************************************************************
 * Dynamic Museum Walk (c) by Scott Maday, Nathon Sexton, Patel Deepkumar, 
 * Noah Hylton, Scout Doran, Travis Ledbetter
 * 
 * Dynamic Museum Walk is licensed under a
 * Creative Commons Attribution-ShareAlike 4.0 International License.
 * 
 * You should have received a copy of the license along with this
 * work. If not, see <http://creativecommons.org/licenses/by-sa/4.0/>.
 * 
 * Authors: Scott Maday
 *****************************************************************************/
?>
<div>
	<a class="button" href="<?= $this->url("museum/action", ["action" => "generate"]); ?>">
		Museum Walk
	</a>
        
</div>
